blank_issues_enabled: false
contact_links:
  - name: Usage Questions
    url: https://stackoverflow.com/questions/tagged/autofac
    about: Want to know how to do something? We monitor questions tagged `autofac` on Stack Overflow! Ask there!
